spring.application.name=example

server.port=${SERVER_PORT:8080}


#url de la base de datos postgresql a la que se conectara a la aplicacion
spring.datasource.url=jdbc:postgresql://localhost:5432/example
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect